apiVersion: v1
kind: Service
metadata:
  name: frontend-green
  namespace: taprav-fri
spec:
  type: ClusterIP
  selector:
    app: frontend
    version: green
  ports:
    - port: 3000
      targetPort: 3000
