apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server (for testing - has higher rate limits)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address for Let's Encrypt account
    email: mb2889@student.uni-lj.si
    # Private key for ACME account
    privateKeySecretRef:
      name: letsencrypt-staging
    # HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
